version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/Devops23

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install react-simple-chatbot --save  

      - run:
          name: Run tests
          command: npm test  

      - run:
          name: Build artifacts
          command: npm run build  

  test:
    docker:
      - image: circleci/node:14

    working_directory: ~/Devops23

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install react-simple-chatbot --save  

      - run:
          name: Run Mocha tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Deploy to DEPLOY$(date +%Y%m%d)
          command: |
            mkdir -p DEPLOY$(date +%Y%m%d)
            cp -r example/* DEPLOY$(date +%Y%m%d)/
      - store_artifacts:
        path: DEPLOY$(date +%Y%m%d)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
