version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/Devops23

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install react-simple-chatbot --save  

      - run:
          name: Run tests
          command: npm test  

      - run:
          name: Build artifacts
          command: npm run build  

  test:
    docker:
      - image: circleci/node:14

    working_directory: ~/Devops23

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install react-simple-chatbot --save  

      - run:
          name: Run Mocha tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
#Add datetime
      - run:
          name: Set DATETIME variable
          command: |
            export DATETIME=$(date "+%Y%m%d")
            echo "DATETIME=$DATETIME" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Deploy to DEPLOY$(date "+%Y%m%d")
          command: |
            mkdir -p DEPLOY$DATETIME
            cp -r example/* DEPLOY$DATETIME/

      - store_artifacts:
          path: DEPLOY$DATETIME
          destination: artifact-file

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
