version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/Devops23

    steps:
      - checkout

      - run:
          name: Install dependencies
<<<<<<< HEAD
          command: npx mocha tests/helpers/setup.mjs tests/**/*.spec.mjs
=======
          command: npx mocha tests/helpers/setup.mjs tests/**/*.spec.js
>>>>>>> ab7cd1e (change file)

  test:
    docker:
      - image: circleci/node:14

    working_directory: ~/Devops23

    steps:
      - checkout

      - run:
          name: Run Mocha tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main

